"""classes added

Revision ID: 75f2ea43688a
Revises: 
Create Date: 2024-08-01 19:06:31.413506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f2ea43688a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('destination_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destination_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('destination_id')
    )
    op.create_table('travel_essentials',
    sa.Column('travelessential_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('travelessential_name', sa.String(length=100), nullable=True),
    sa.Column('travelessential_description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('travelessential_id')
    )
    op.create_table('user_admin',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=200), nullable=False),
    sa.Column('user_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('blogs',
    sa.Column('blog_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blog_title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.destination_id'], ),
    sa.PrimaryKeyConstraint('blog_id')
    )
    op.create_table('itineraries',
    sa.Column('itinerary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.destination_id'], ),
    sa.PrimaryKeyConstraint('itinerary_id')
    )
    op.create_table('location_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('local_tips', sa.Text(), nullable=True),
    sa.Column('best_time_to_visit', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.destination_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.blog_id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.destination_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('subheadings',
    sa.Column('subheading_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subheading_title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.blog_id'], ),
    sa.PrimaryKeyConstraint('subheading_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subheadings')
    op.drop_table('images')
    op.drop_table('location_details')
    op.drop_table('itineraries')
    op.drop_table('blogs')
    op.drop_table('user_admin')
    op.drop_table('travel_essentials')
    op.drop_table('destinations')
    # ### end Alembic commands ###
