"""Change in field

Revision ID: b11bb60aad34
Revises: e1420793e4c8
Create Date: 2024-08-05 19:34:00.562680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b11bb60aad34'
down_revision = 'e1420793e4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_essentials', schema=None) as batch_op:
        batch_op.alter_column('travelessential_description',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_essentials', schema=None) as batch_op:
        batch_op.alter_column('travelessential_description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
