"""Create itinerary_days table

Revision ID: e1420793e4c8
Revises: 75f2ea43688a
Create Date: 2024-08-05 18:42:50.928929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1420793e4c8'
down_revision = '75f2ea43688a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_days',
    sa.Column('day_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.itinerary_id'], ),
    sa.PrimaryKeyConstraint('day_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary_days')
    # ### end Alembic commands ###
